#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  1 15:17:25 2021
@brief scripts to work with exports from GRU website for registration Data (player info)
@author: alec
"""

import pandas as pd

class Players(pd.DataFrame):
    @property
    def _constructor(self):
        return Players
    @property
    def _constructor_sliced(self):
        return pd.Series
    
    def __init__(self,*args,**kwargs):
        '''@brief constructor'''
        super().__init__(*args,**kwargs)
        #self.set_index_as_names(inplace=True) # use names as index
    
    def set_index_as_names(self,**kwargs):
        '''@brief set the index as the player first_name last_name'''
        name_idx = pd.Index(self['first_name']+' '+self['last_name'],name='name')
        return self.set_index(name_idx,**kwargs)
    
    def get_vector(self,**kwargs):
        '''@brief get the vector from the data provided. return a Series'''
        vector_keys = ['HighestLevel5','Throws','Ath']
        pass
    
    def get_sub_list(self):
        '''@brief get a list of possible subs (i.e. pull the watilist with contact info)'''
        contact_keys = ['email_address','primary_phone_number']
        info_keys = ['gender']
        waitlisted = players[players['status']=='waitlisted']
        return waitlisted[['first_name','last_name']+contact_keys+info_keys]
        
    @classmethod 
    def from_csv(cls,path,**kwargs):
        return cls(pd.read_csv(path,**kwargs))
        
    
    
if __name__=='__main__':
    
    path = '/data/downloads/2021-Fall-Broomfield-League_2021-09-01-14_51.csv'
    players = Players.from_csv(path)
    possible_subs = players.get_sub_list()
